name: Create Archive Release

on:
  push:
    tags:
      - "v*"

  # Allow running manually from the actions tab
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Release
        run: |
          node script/set-module-urls.mjs "${{github.ref_name}}"
          gh release create "${{github.ref_name}}" --title "${{github.ref_name}}" --notes "${{github.ref_name}}" plutonium-*.zip module-*.json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
